enum responses {
  SUCCESS_SAVE = 0,
  ALREADY_EXIST,
  SERVER_ERROR,
  SUCCESS_LOGIN,
  FAILED_LOGIN,
  SUCCESS,
  USER_DONT_EXIST,
  WRONG_IDS_ON_DATA,
  UNEXPECTED_ERROR,
  TELEGRAM_USER_DONT_EXIST,
  PARAMETER_INACTIVE,
  COW_INACTIVE,
  USER_INACTIVE,
  USER_NOT_ADMIN,
}
export {responses}